Added initial Dockerfile and .dockerignore for backend
Project-Dahlia/Dahlia pull request #40
Opened 2024-03-01 01:03 UTC by jaysabe

## Pull Request

### Description

Briefly describe the purpose of this pull request.
Created and added initial Dockerfile and .dockerignore for backend. 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)\
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### Issue ticket number and link

[DAH-](https://igit.atlassian.net/jira/software/projects/DAH/boards/4?selectedIssue=DAH-)

### Checklist

- [ ] Self-reviewed my code prior to submission.
- [ ] Tests have been added or updated (if applicable).
- [ ] Documentation has been updated (if applicable).
- [ ] Screenshots added (if applicable).
- [ ] This PR is ready for review.

### Screenshots

2024-03-01 03:27 UTC, jaysabe commented
looks like I still missed something in commitlint. Will follow up tomorrow on this.

2024-03-01 03:29 UTC, RickyC0626 commented
> looks like I still missed something in commitlint. Will follow up tomorrow on this.

Ah, looks like you can't have uppercase in commit due to convention.

2024-03-02 00:45 UTC, RickyC0626 requested changes

2024-03-02 00:45 UTC, RickyC0626 commented on backend/Dockerfile
> +# Set Yarn version
**nitpick:** This is probably meant to be `npm`

2024-03-02 00:45 UTC, RickyC0626 commented on backend/Dockerfile
> +FROM node:18.19.0-alpine
**suggestion:** To keep versioning consistent with CI, let's use `20.11.1-alpine`

2024-03-06 15:21 UTC, RickyC0626 approved these changes

2024-03-06 15:24 UTC, xamdoo approved these changes

2024-03-06 15:24 UTC, merged