ci(backend): setup lint workflow
Project-Dahlia/Dahlia pull request #43
Opened 2024-03-01 14:30 UTC by xamdoo

### *What* change does this PR introduce?

Added backend lint workflow to automate the execution of backend linting tools on the codebase.
### *Why* was this change needed?
This change was implemented to automate backend code quality checks and improve overall code maintainability.

- Closes #21 

### Other information (screenshots)

### Checklist

- [X] 📝 I have reviewed my code prior to submission
- [X] ❔ Issue number has been linked (if applicable)
- [ ] 🧪 Tests have been added or updated (if applicable)
- [ ] 📖 Documentation has been updated (if applicable)
- [ ] 📸 Screenshots added (if applicable)

2024-03-01 14:40 UTC, RickyC0626 requested changes
In `package.json`, can we update the lint scripts to be similar to the ones in `frontend/`? For example:
```json
"lint": "eslint . && prettier --check .",
"lint:fix": "eslint --fix && prettier --write .",
```

2024-03-01 14:40 UTC, RickyC0626 commented on .github/workflows/backend-lint.yml
> +      - name: Lint with Eslint
**nitpick:** `Run linters` would make more sense since we may be running more than just ESLint.

2024-03-02 11:36 UTC, CeeJayyy007 approved these changes

2024-03-02 14:32 UTC, RickyC0626 approved these changes

2024-03-02 14:33 UTC, merged