chore(setup): `lerna` for monorepo package versioning
Project-Dahlia/Dahlia pull request #56
Opened 2024-03-02 17:04 UTC by xamdoo

### *What* change does this PR introduce?

This PR sets up Lerna for managing multiple packages within a single repository
### *Why* was this change needed?
Lerna would handle shared dependencies among packages within the monorepo reducing duplication and simplifying installation

- Closes #48 

### Other information (screenshots)

### Checklist

- [X] 📝 I have reviewed my code prior to submission
- [X] ❔ Issue number has been linked (if applicable)
- [ ] 🧪 Tests have been added or updated (if applicable)
- [ ] 📖 Documentation has been updated (if applicable)
- [ ] 📸 Screenshots added (if applicable)

2024-03-02 17:19 UTC, RickyC0626 requested changes
Remember to update the working directories in GitHub Actions workflows too.

2024-03-02 17:19 UTC, RickyC0626 commented on lerna.json
> +  "version": "0.0.0"
**chore:** Let's bump to version `0.0.1`

2024-03-02 17:22 UTC, RickyC0626 commented on packages/backend/package.json
**chore:** Set version to `0.0.1` here as well.

2024-03-02 18:00 UTC, xamdoo commented on packages/backend/package.json
does this apply to both frontend and backend packages or just the backend?

2024-03-02 18:26 UTC, RickyC0626 commented on packages/backend/package.json
Oh right, both. I think an easy way to do this is use the `lerna version` command with the flags `--no-changelog` and `--no-git-tag-version`. We can run the same command without flags during actual release.

2024-03-02 18:54 UTC, RickyC0626 submitted a review, later dismissed
Looks good!

2024-03-05 23:12 UTC, jaysabe requested changes
Looks like we'll need to address merging conflicts before proceeding with the merge to dev.

2024-03-06 03:52 UTC, RickyC0626 commented
Since we have new updates to the original files, we probably have to move the directories to `packages/` again. `git mv` will be helpful for those. Perhaps 1 commit for each directory. After renaming we can apply the `lerna` changes on top.

2024-03-06 14:41 UTC, RickyC0626 approved these changes

2024-03-06 15:10 UTC, CeeJayyy007 approved these changes
**praise:** Awesome work!

2024-03-06 15:25 UTC, merged